return {

    [3726919761] = {
        Name    = "Cursed Gear",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/36864a859d2e1641ff75da81e971f9fe.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/248ac237cd25b7f8bc00967aa75b3241.lua",
    },

    [8524572339] = {
        Name    = "bridger: WESTERN",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/00f66c6113c62438df3ad3ba4ab54ddc.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/62fae3fc8ed63cf34669218569de1eb0.lua",
    },


    [5130394318] = {
        Name    = "Bizarre Lineage",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/8e596a14b226166df1768ba08d56d4b7.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/1d81a6853a3d06f84ff080a9df897512.lua",
    },

    [4658598196] = {
        Name    = "AOTR",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/5ca5aecc9b4650eea56cfcf9418fe87a.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/083df767880b4503a08252f478a1e8cf.lua",
    },

    [6490954291] = {
        Name    = "Ghoul Re",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/10de03d3dcd49cf0d5deaa7f0e58ee02.lua",
        FreeUrl = nil,
    },

    [4818959878] = {
        Name    = "Mashles",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/7722103e5fe735cd0631f9cc15ce7100.lua",
        FreeUrl = nil,
    },

    [9872691883] = {
        Name    = "Everwind",
        PaidUrl = nil,
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/bc75c1b6486e53d3ea5cc74a0b559498.lua",
    },

    [6760085372] = {
        Name    = "Jujutsu Zero",
        PaidUrl = nil,
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/18eb981418ced3ee300d434394f254fb.lua",
    },

    [9186719164] = {
        Name    = "Sailor Piece",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/60b92b9536dd001f847cf6dfa6baf96a.lua",
        FreeUrl = nil,
    },

    [578392296] = {
        Name    = "ABA",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/c9b0fca9ee7806da690cd40c77751691.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/fb277df44e3bc5d7b727588f9302c1d5.lua",
    },

    [648454481] = {
        Name    = "GPO",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/61102a9b811fe8273401dd82e87af377.lua",
        FreeUrl = nil,
    },

    [3646793294] = {
        Name    = "Paradox",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/ef92f3d02260fe6c32d8d0e28fffd566.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/d910afd350100dfc9ed8c8b1580784fd.lua",
    },

    [7800001548] = {
        Name    = "Exordia",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/5353c3b548ae284d8f5d8f47fec83398.lua",
        FreeUrl = nil,
    },

    [9271746647] = {
        Name    = "Baseplate",
        PaidUrl = "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
        FreeUrl = "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
    },

}
